metadata:
  name: hazelcastconfig
data:
  hazelcast.xml: |
    <hazelcast xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.6.xsd"
               xmlns="http://www.hazelcast.com/schema/config"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <properties>
        <!-- only necessary prior Hazelcast 3.8 -->
        <property name="hazelcast.discovery.enabled">true</property>
      </properties>

      <network>
        <join>
          <!-- deactivate normal discovery -->
          <multicast enabled="false"/>
          <tcp-ip enabled="false" />

          <!-- activate the Kubernetes plugin -->
          <discovery-strategies>
            <discovery-strategy enabled="true"
                class="com.hazelcast.kubernetes.HazelcastKubernetesDiscoveryStrategy">

              <properties>
                <!-- configure discovery service API lookup -->
                 <property name="service-label-name">cluster01</property>
                  <property name="service-label-value">true</property>
                <property name="namespace">myproject</property>
              </properties>
            </discovery-strategy>
          </discovery-strategies>
        </join>
      </network>
    </hazelcast>